CREATE TABLE IF NOT EXISTS `MEMBER` (
    `MEMBER_ID`	BIGINT	NOT NULL  AUTO_INCREMENT,
    `EMAIL`	VARCHAR(100)	NOT NULL,
    `PASSWORD`	VARCHAR(30)	NOT NULL,
    `NAME`	VARCHAR(50)	NOT NULL,
    `NICKNAME`	VARCHAR(100)	NOT NULL,
    `GENDER`	VARCHAR(1)	NULL,
    `BIRTHDATE`	DATE	NULL,
    `PHONE_NUMBER`	VARCHAR(13)	NULL,
    `SIGNUP_DATE`	DATETIME	NOT NULL,
    `WITHDRAWAL_DATE`	DATETIME	NULL,
    `LAST_MODIFIED_BY`	VARCHAR(50)	NULL,
    `LAST_MODIFIED_AT`	DATETIME	NULL,
    PRIMARY KEY (`MEMBER_ID`)
);


CREATE TABLE IF NOT EXISTS `BOOK_REPORT` (
   `BOOK_REPORT_ID`	BIGINT	NOT NULL  AUTO_INCREMENT,
   `BOOK_ID`	BIGINT	NOT NULL,
   `MEMBER_ID`	BIGINT	NOT NULL,
   `IS_PUBLIC`	VARCHAR(1)	NOT NULL,
   `BOOK_REPORT_TITLE`	VARCHAR(500)	NOT NULL,
   `BOOK_REPORT_CONTENT`	TEXT	NOT NULL,
   `CREATED_BY`	VARCHAR(50)	NOT NULL,
   `CREATED_AT`	DATETIME	NOT NULL,
   `LAST_MODIFIED_BY`	VARCHAR(50)	NULL,
   `LAST_MODIFIED_AT`	DATETIME	NULL,
   `IS_DELETED`	VARCHAR(1)	NULL,
   `DELETED_AT`	DATETIME	NULL,
    PRIMARY KEY (`BOOK_REPORT_ID`)
);